questions =  [
    {"id": 0, "question":  "Minimum wage laws can raise wages above what some employers are able to sustain.", "effects": {"right": 1}},
    {"id": 1, "question":  "Self-interest is an important driver of economic growth.", "effects": {"right": 1}},
    {"id": 2, "question":  "Most people’s income reflects their contribution to society.", "effects": {"right": 1}},
    {"id": 3, "question":  "Claims of exploitation in modern economies are often exaggerated.", "effects": {"right": 1}},
    {"id": 4, "question":  "Communism can function effectively on a large scale.", "effects": {"right": -1}},
    {"id": 5, "question":  "Markets with minimal government regulation produce more economic output than heavily regulated markets.", "effects": {"right": 1}},
    {"id": 6, "question":  "Hard work is the main factor in success in society.", "effects": {"right": 1}},
    {"id": 7, "question":  "Employers who cannot afford a higher minimum wage may be operating on an unsustainable business model.", "effects": {"right": -1}},
    {"id": 8, "question":  "The state should redistribute wealth from higher earners to support those who earn lower income.", "effects": {"right": -1}},
    {"id": 9, "question":  "Access to basic necessities such as food, housing, and healthcare should be guaranteed by the government.", "effects": {"right": -1}},
    {"id": 10, "question": "A strong social safety net is necessary, even if it leads to higher taxes.", "effects": {"right": -1}},
    {"id": 11, "question": "Collective welfare should take precedence over individual profit.", "effects": {"right": -1}},
    {"id": 12, "question": "Basic infrastructure, such as roads, should be publicly owned.", "effects": {"right": -1}},
    {"id": 13, "question": "Economic outcomes are ultimately influenced more by personal circumstances than by individual choices.", "effects": {"right": -1}},
    {"id": 14, "question": "Economic inequality should be reduced through government intervention.", "effects": {"right": -1}},
    {"id": 15, "question": "Government surveillance can be justified to combat serious threats to society, such as terrorism.", "effects": {"auth": 1}},
    {"id": 16, "question": "Authority figures can play a positive role in maintaining a stable society.", "effects": {"auth": 1}},
    {"id": 17, "question": "Authority is necessary for a government to function effectively.", "effects": {"auth": 1}},
    {"id": 18, "question": "Government involvement can improve how organizations are managed.", "effects": {"auth": 1}},
    {"id": 19, "question": "Maintaining social order is more important than maximizing individual freedom.", "effects": {"auth": 1}},
    {"id": 20, "question": "Expanding state power can be an effective way to fight crime.", "effects": {"auth": 1}},
    {"id": 21, "question": "In times of crisis, safety should take precedence over personal freedoms.", "effects": {"auth": 1}},
    {"id": 22, "question": "Justice systems should prioritize punishment that reflects the severity of the offense.", "effects": {"auth": 1}},
    {"id": 23, "question": "Governments should have little involvement in individuals’ personal lives.", "effects": {"auth": -1}},
    {"id": 24, "question": "Citizens should be able to choose their political leaders.", "effects": {"auth": -1}},
    {"id": 25, "question": "Justice systems should focus more on rehabilitation than punishment.", "effects": {"auth": -1}},
    {"id": 26, "question": "Privacy should not be sacrificed in exchange for greater public safety.", "effects": {"auth": -1}},
    {"id": 27, "question": "Government power is more likely to be abused than individual freedoms.", "effects": {"auth": -1}},
    {"id": 28, "question": "Freedom of speech should not be absolute.", "effects": {"auth": 1}},
    {"id": 29, "question": "Policing systems are primarily designed to maintain existing social structures.", "effects": {"auth": -1}},
    {"id": 30, "question": "Laws that are widely unpopular are more likely to be unjust.", "effects": {"auth": -1}},
    {"id": 31, "question": "Consensual actions between adults should be legal.", "effects": {"prog": 1}},
    {"id": 32, "question": "Religious beliefs should be separate from policy.", "effects": {"prog": 1}},
    {"id": 33, "question": "All peoples should have unconditional bodily autonomy.", "effects": {"prog": 1}},
    {"id": 34, "question": "Nudity should not be considered inherently inappropriate.", "effects": {"prog": 1}},
    {"id": 35, "question": "Systemic discrimination exists and should be addressed through reform.", "effects": {"prog": 1}},
    {"id": 36, "question": "Gender identity is distinct from biological sex.", "effects": {"prog": 1}},
    {"id": 37, "question": "Laws should be based on universal ethics rather than cultural traditions.", "effects": {"prog": 1}},
    {"id": 38, "question": "All individuals should have basic human rights, regardless of their actions.", "effects": {"prog": 1}},
    {"id": 39, "question": "Same-sex marriage and adoption should not be protected by law.", "effects": {"prog": -1}},
    {"id": 40, "question": "Adoption policies should emphasize traditional family values and structures.", "effects": {"prog": -1}},
    {"id": 41, "question": "Recreational marijuana should be prohibited.", "effects": {"prog": -1}},
    {"id": 42, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 43, "question": "Victimless crimes such as gambling or prostitution should be criminalized.", "effects": {"prog": -1}},
    {"id": 44, "question": "Traditional family structures are important and should be preserved.", "effects": {"prog": -1}},
    {"id": 45, "question": "Undocumented immigration should be punished by law.", "effects": {"prog": -1}},
    {"id": 46, "question": "Cultural diversity is necessary for a prosperous society.", "effects": {"prog": 1}}];
