questions =  [
    {"id": 0, "question": "Free market capitalism is a desirable economic system.", "effects": {"right": 1}},
    {"id": 1, "question": "Social welfare is far too accessible and is often abused.", "effects": {"right": 1}},
    {"id": 2, "question": "The minimum wage is currently what it ought to be.", "effects": {"right": 1}},
    {"id": 3, "question": "It is \"human nature\" to be greedy.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.", "effects": {"right": 1}},
    {"id": 5, "question": "Communism is utopian and cannot function properly on a large scale.", "effects": {"right": 1}},
    {"id": 6, "question": "Taxation is theft.", "effects": {"right": 1}},
    {"id": 7, "question": "Hard work is the biggest factor behind success in society.", "effects": {"right": 1}},
    {"id": 8, "question": "Corporations require strong government regulation to prevent harm.", "effects": {"right": -1}},
    {"id": 9, "question": "A government that provides for everyone is an inherently good idea.", "effects": {"right": -1}},
    {"id": 10, "question": "The current welfare system should be expanded to further combat inequality.", "effects": {"right": -1}},
    {"id": 11, "question": "Collective welfare should take precedent over individual profit.", "effects": {"right": -1}},
    {"id": 12, "question": "Basic services, such as roads, should be publicly owned.", "effects": {"right": -1}},
    {"id": 13, "question": "Social class is the primary division of society.", "effects": {"right": -1}},
    {"id": 14, "question": "Economic inequality should be reduced through government intervention.", "effects": {"right": -1}},
    {"id": 15, "question": "Government is a necessary evil to combat terrorism.", "effects": {"auth": 1}},
    {"id": 16, "question": "Authority figures, if morally correct, are a good thing for society.", "effects": {"auth": 1}},
    {"id": 17, "question": "Any government needs strong authority in order to function properly.", "effects": {"auth": 1}},
    {"id": 18, "question": "Organizations work best when the government is involved in their management and organization.", "effects": {"auth": 1}},
    {"id": 19, "question": "Maintaining social order is more important than individual freedom.", "effects": {"auth": 1}},
    {"id": 20, "question": "The state's power should be expanded to prevent crime.", "effects": {"auth": 1}},
    {"id": 21, "question": "In times of crisis, safety should take precedent over personal freedom.", "effects": {"auth": 1}},
    {"id": 22, "question": "Punitive justice should apply to all crimes.", "effects": {"auth": 1}},
    {"id": 23, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 24, "question": "Democracy is a fundamental virtue that society should implement.", "effects": {"auth": -1}},
    {"id": 25, "question": "The justice system should be reformed to be less harsh.", "effects": {"auth": -1}},
    {"id": 26, "question": "Counter-terrorism has infringed on our privacy rights.", "effects": {"auth": -1}},
    {"id": 27, "question": "Law and order is a flawed and often misused buzzword.", "effects": {"auth": -1}},
    {"id": 28, "question": "The primary role of the police is to uphold existing power structures through force.", "effects": {"auth": -1}},
    {"id": 29, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 30, "question": "Regardless of what the act is, if it's consensual, it should be legally permissible.", "effects": {"prog": 1}},
    {"id": 31, "question": "Even bad things, such as self harm, should be legally permissible to inflict upon oneself.", "effects": {"prog": 1}},
    {"id": 32, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nudism is perfectly natural.", "effects": {"prog": 1}},
    {"id": 34, "question": "Systemic racism is a reality and must be addressed through reform.", "effects": {"prog": 1}},
    {"id": 35, "question": "Gender is a social construct, and separate from biological sex.", "effects": {"prog": 1}},
    {"id": 36, "question": "Laws based on cultural values, rather than ones that do not take culture into account, are desirable.", "effects": {"prog": 1}},
    {"id": 37, "question": "Everyone, including the most violent criminals, should have the human rights.", "effects": {"prog": 1}},
    {"id": 38, "question": "I oppose same sex marriage and adoption.", "effects": {"prog": -1}},
    {"id": 39, "question": "Adoption eligibility should include emphasis on traditional family environments.", "effects": {"prog": -1}},
    {"id": 40, "question": "Drugs are harmful and should be banned.", "effects": {"prog": -1}},
    {"id": 41, "question": "I support the death penalty.", "effects": {"prog": -1}},
    {"id": 42, "question": "Victimless crimes, such as gambling and prostitution, should be punished.", "effects": {"prog": -1}},
    {"id": 43, "question": "Religious values should be implemented in the government and school system.", "effects": {"prog": -1}},
    {"id": 44, "question": "Traditional family structures are vital, and thus should be preserved.", "effects": {"prog": -1}},
    {"id": 45, "question": "Undocumented immigration should be punished in one way or another.", "effects": {"prog": -1}}
];
